Mary had a bigger lamb. 
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.
Mary had a bigger lamb.